#cloud-config
write_files:
- encoding: b64
  content: IyEvYmluL2Jhc2ggLXgKCiMgYXR0YWNoIHRoZSBFTkkKYXdzIGVjMiBhdHRhY2gtbmV0d29yay1pbnRlcmZhY2UgXAogIC0tcmVnaW9uICIkKC9vcHQvYXdzL2Jpbi9lYzItbWV0YWRhdGEgLXogfCBzZWQgJ3MvcGxhY2VtZW50OiBcKC4qXCkuJC9cMS8nKSIgXAogIC0taW5zdGFuY2UtaWQgIiQoL29wdC9hd3MvYmluL2VjMi1tZXRhZGF0YSAtaSB8IGN1dCAtZCcgJyAtZjIpIiBcCiAgLS1kZXZpY2UtaW5kZXggMSBcCiAgLS1uZXR3b3JrLWludGVyZmFjZS1pZCAiJHtlbmlfaWR9IgoKIyBzdGFydCBTTkFUCnN5c3RlbWN0bCBlbmFibGUgc25hdApzeXN0ZW1jdGwgc3RhcnQgc25hdA==
  path: "/opt/nat/runonce.sh"
  permissions: "0755"
- encoding: b64
  content: IyEvYmluL2Jhc2gKc2V0IC14CgojIHdhaXQgZm9yIGV0aDEKd2hpbGUgISBpcCBsaW5rIHNob3cgZGV2IGV0aDE7IGRvCiAgc2xlZXAgMQpkb25lCgojIGVuYWJsZSBJUCBmb3J3YXJkaW5nIGFuZCBOQVQKc3lzY3RsIC1xIC13IG5ldC5pcHY0LmlwX2ZvcndhcmQ9MQpzeXNjdGwgLXEgLXcgbmV0LmlwdjQuY29uZi5ldGgxLnNlbmRfcmVkaXJlY3RzPTAKaXB0YWJsZXMgLXQgbmF0IC1BIFBPU1RST1VUSU5HIC1vIGV0aDEgLWogTUFTUVVFUkFERQoKIyBwcmV2ZW50IHNldHRpbmcgdGhlIGRlZmF1bHQgcm91dGUgdG8gZXRoMCBhZnRlciByZWJvb3QKcm0gLWYgL2V0Yy9zeXNjb25maWcvbmV0d29yay1zY3JpcHRzL2lmY2ZnLWV0aDAKCiMgc3dpdGNoIHRoZSBkZWZhdWx0IHJvdXRlIHRvIGV0aDEKaXAgcm91dGUgZGVsIGRlZmF1bHQgZGV2IGV0aDAKCiMgd2FpdCBmb3IgbmV0d29yayBjb25uZWN0aW9uCmN1cmwgLS1yZXRyeSAxMCBodHRwOi8vd3d3LmV4YW1wbGUuY29tCgojIHJlZXN0YWJsaXNoIGNvbm5lY3Rpb25zCnN5c3RlbWN0bCByZXN0YXJ0IGFtYXpvbi1zc20tYWdlbnQuc2VydmljZQ==
  path: "/opt/nat/snat.sh"
  permissions: "0755"
- encoding: b64
  content: W1VuaXRdCkRlc2NyaXB0aW9uID0gU05BVCB2aWEgRU5JIGV0aDEKCltTZXJ2aWNlXQpFeGVjU3RhcnQgPSAvb3B0L25hdC9zbmF0LnNoClR5cGUgPSBvbmVzaG90CgpbSW5zdGFsbF0KV2FudGVkQnkgPSBtdWx0aS11c2VyLnRhcmdldA==
  path: "/etc/systemd/system/snat.service"

runcmd:
- [ "/opt/nat/runonce.sh" ]